[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DROVER_PLATFORM_ARDUINO


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DROVER_PLATFORM_ESP32
    -Og
    -g3

monitor_speed = 115200

upload_protocol = esptool
debug_tool = esp-prog
debug_init_break = tbreak setup



[platformio]
default_envs = esp32dev