[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DROVER_PLATFORM_ARDUINO

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DROVER_PLATFORM_ESP32
monitor_speed = 115200

[platformio]
default_envs = esp32dev
